version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./storage/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    restart: unless-stopped
    working_dir: /app
    build: .
    container_name: go_container
    ports:
      - "8084:8084"
    volumes:
      - .:/app
    environment:
      STORAGE_TYPE: postgres # postgres | in-memory
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: postgres
    depends_on:
      postgresql:
        condition: service_healthy
