name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.22.3'

      - name: Install dependencies
        run: go mod download

      - name: Run tests for in-memory storage
        run: go test ./tests/in-memory/in-memory_test.go -v
        
      - name: Run tests for postgresql storage
        run: go test ./tests/postgres/postgres_test.go -v
